title: Tobias (Tobee) Hansen
description: A portfolio about Tobee
logo: /assets/img/Tobee_GG_logo.jpeg
#show_downloads: true
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have o 
#background: dark
favicon: "favicon.png"
google_analytics: G-Y3XEH801X3
mode: dark
